// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	player "github.com/antonbaumann/spotify-jukebox/player"
)

// PlayerCollection is an autogenerated mock type for the PlayerCollection type
type PlayerCollection struct {
	mock.Mock
}

// GetPlayer provides a mock function with given fields: ctx, sessionID
func (_m *PlayerCollection) GetPlayer(ctx context.Context, sessionID string) (*player.Player, error) {
	ret := _m.Called(ctx, sessionID)

	var r0 *player.Player
	if rf, ok := ret.Get(0).(func(context.Context, string) *player.Player); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*player.Player)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetPaused provides a mock function with given fields: ctx, sessionID, paused
func (_m *PlayerCollection) SetPaused(ctx context.Context, sessionID string, paused bool) error {
	ret := _m.Called(ctx, sessionID, paused)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, sessionID, paused)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetPlayer provides a mock function with given fields: ctx, sessionID, newPlayer
func (_m *PlayerCollection) SetPlayer(ctx context.Context, sessionID string, newPlayer *player.Player) error {
	ret := _m.Called(ctx, sessionID, newPlayer)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *player.Player) error); ok {
		r0 = rf(ctx, sessionID, newPlayer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetProgress provides a mock function with given fields: ctx, sessionID, progress
func (_m *PlayerCollection) SetProgress(ctx context.Context, sessionID int, progress int) error {
	ret := _m.Called(ctx, sessionID, progress)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, sessionID, progress)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
