// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import song "github.com/antonbaumann/spotify-jukebox/song"

// SongCollection is an autogenerated mock type for the SongCollection type
type SongCollection struct {
	mock.Mock
}

// AddSong provides a mock function with given fields: ctx, sessionID, newSong
func (_m *SongCollection) AddSong(ctx context.Context, sessionID string, newSong *song.Model) error {
	ret := _m.Called(ctx, sessionID, newSong)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *song.Model) error); ok {
		r0 = rf(ctx, sessionID, newSong)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSongByID provides a mock function with given fields: ctx, sessionID, songID
func (_m *SongCollection) GetSongByID(ctx context.Context, sessionID string, songID string) (*song.Model, error) {
	ret := _m.Called(ctx, sessionID, songID)

	var r0 *song.Model
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *song.Model); ok {
		r0 = rf(ctx, sessionID, songID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*song.Model)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, sessionID, songID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSongs provides a mock function with given fields: ctx, sessionID
func (_m *SongCollection) ListSongs(ctx context.Context, sessionID string) ([]*song.Model, error) {
	ret := _m.Called(ctx, sessionID)

	var r0 []*song.Model
	if rf, ok := ret.Get(0).(func(context.Context, string) []*song.Model); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*song.Model)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveSong provides a mock function with given fields: ctx, sessionID, songID
func (_m *SongCollection) RemoveSong(ctx context.Context, sessionID string, songID string) error {
	ret := _m.Called(ctx, sessionID, songID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, sessionID, songID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VoteDown provides a mock function with given fields: ctx, sessionID, songID, username
func (_m *SongCollection) VoteDown(ctx context.Context, sessionID string, songID string, username string) (int, error) {
	ret := _m.Called(ctx, sessionID, songID, username)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) int); ok {
		r0 = rf(ctx, sessionID, songID, username)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, sessionID, songID, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VoteUp provides a mock function with given fields: ctx, sessionID, songID, username
func (_m *SongCollection) VoteUp(ctx context.Context, sessionID string, songID string, username string) (int, error) {
	ret := _m.Called(ctx, sessionID, songID, username)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) int); ok {
		r0 = rf(ctx, sessionID, songID, username)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, sessionID, songID, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
